######
# Site settings
title:          Alex Stevens
description:    "University of Denver CS"
url:            #"https://chesterhow.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Alex Stevens
  url:          #https://chester.how
  email:        alex.stevens@du.edu

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       30

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
